trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_IMAGE_NAME: my-mcp-server
  DOCKER_IMAGE_TAG: latest
  ACR_NAME: mcpacr0101  # if using Azure Container Registry

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'DES-ACR'
    repository: $(DOCKER_IMAGE_NAME)
    command: buildAndPush
    Dockerfile: '**/Dockerfile'
    tags: |
      $(DOCKER_IMAGE_TAG)

# - task: AzureWebAppContainer@2
#   displayName: Deploy to Azure Web App
#   inputs:
#     azureSubscription: '<Service Connection to Azure>'
#     appName: 'my-mcp-container'
#     containers: '$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)'
